version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    ignore:
      - dependency-name: engine.io
      - dependency-name: uuid
      - dependency-name: engine.io-client
      - dependency-name: standard
